import type { Fundraiser } from "@/types/fundraiser";

export const mockFundraisers: Fundraiser[] = [
	{
        id: "fundraiser-1", 
        name: "July Pandas",
        description: "Partner with Pandas",
        notes: "Collect Money",
        startDate: new Date("07-11-2025"),
        status: "Active",
        distributionMethod: "Equal",
        collectionType: "Check",
        scope: "All",
	},
	{
        id: "fundraiser-2",
        name: "July Pandas",
        description: "Pandas Fundraiser",
        notes: "Need to confirm",
        startDate: new Date("7-12-2025"),
        status: "Draft",
        distributionMethod: "Equal",
        collectionType: "Check",
        scope: "All",
	},	
    {
        id: "fundraiser-3",
        name: "January Fundrailser",
        description: "Raised Funds in jan",
        notes: "done",
        startDate: new Date("1-1-2025"),
        status: "Completed",
        distributionMethod: "Equal",
        collectionType: "Check",
        scope: "All",
	},	
    {
        id: "fundraiser-4",
        name: "August Pandasd",
        description: "Partner with Pandas",
        notes: "not doing",
        startDate: new Date("8-21-2025"),
        status: "Cancelled",
        distributionMethod: "Equal",
        collectionType: "Check",
        scope: "All",
	},
];
